title:               雲石知产CloudStoneIP——跨境电商知识产权服务
url:                 https://felixhuan.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              雲石知产
  url:               felixhuan.github.io
  email:             liuhuan@cloudstoneip.com

