title:               雲石CloudStone——跨境电商一站式法律服务律师团队
url:                 https://felixhuan.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              雲石CloudStone律师
  url:               felixhuan.github.io
  email:             liuhuan@cloudstoneip.com

